import "./globals.css";
import type { Metadata } from "next";

import { Header } from "./_components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-secondaryC min-w-screen min-h-screen antialiased`}>
        <Header />
        <div className="px-4 md:px-16 xl:px-20 2xl:px-72 py-32 2xl:py-40">
          {children}
        </div>
      </body>
    </html>
  );
}
